export const GET_SUMMONER_SUCCESS = 'GET_SUMMONER_SUCCESS';
export const GET_SUMMONER_FAILURE = 'GET_SUMMONER_FAILURE';

export const GET_MATCH_LIST_SUCCESS = 'GET_MATCH_LIST_SUCCESS';
export const GET_MATCH_LIST_FAILURE = 'GET_MATCH_LIST_FAILURE';

export const GET_MATCH_SUCCESS = 'GET_MATCH_SUCCESS';
export const GET_MATCH_FAILURE = 'GET_MATCH_FAILURE';

export const GET_MATCH_TIMELINE_SUCCESS = 'GET_MATCH_TIMELINE_SUCCESS';
export const GET_MATCH_TIMELINE_FAILURE = 'GET_MATCH_TIMELINE_FAILURE';

export const GET_USER_TIMELINE_DATA = 'GET_USER_TIMELINE_DATA';

export const CLEAR_DATA = 'CLEAR_DATA';
export const REQUEST_START = 'REQUEST_START';
export const REQUEST_END = 'REQUEST_END';
export const ERROR = 'ERROR';

export default {
    GET_SUMMONER_SUCCESS,
    GET_SUMMONER_FAILURE,
    GET_MATCH_LIST_SUCCESS,
    GET_MATCH_LIST_FAILURE,
    GET_MATCH_SUCCESS,
    GET_MATCH_FAILURE,
    GET_MATCH_TIMELINE_SUCCESS,
    GET_MATCH_TIMELINE_FAILURE,
    GET_USER_TIMELINE_DATA,
    CLEAR_DATA,
    REQUEST_START,
    REQUEST_END,
    ERROR,
}