export const GET_SUMMONER_SUCCESS = 'GET_SUMMONER_SUCCESS';
export const GET_SUMMONER_FAILURE = 'GET_SUMMONER_FAILURE';

export const GET_MATCH_LIST_SUCCESS = 'GET_MATCH_LIST_SUCCESS';
export const GET_MATCH_LIST_FAILURE = 'GET_MATCH_LIST_FAILURE';

export const GET_MATCH_SUCCESS = 'GET_MATCH_SUCCESS';
export const GET_MATCH_FAILURE = 'GET_MATCH_FAILURE';

export const GET_MATCH_TIMELINE_SUCCESS = 'GET_MATCH_TIMELINE_SUCCESS';
export const GET_MATCH_TIMELINE_FAILURE = 'GET_MATCH_TIMELINE_FAILURE';

export const GET_USER_DATA = 'GET_USER_DATA';

export const GET_OPPONENT_WINRATES = 'GET_OPPONENT_WINRATES';
export const GET_ALLY_WINRATES = 'GET_ALLY_WINRATES';

export const GET_AGGREGATE_USER_DATA = 'GET_AGGREGATE_USER_DATA';
export const GET_AGGREGATE_MATCH_DATA = 'GET_AGGREGATE_MATCH_DATA';

export default {
    GET_SUMMONER_SUCCESS,
    GET_SUMMONER_FAILURE,
    GET_MATCH_LIST_SUCCESS,
    GET_MATCH_LIST_FAILURE,
    GET_MATCH_SUCCESS,
    GET_MATCH_FAILURE,
    GET_MATCH_TIMELINE_SUCCESS,
    GET_MATCH_TIMELINE_FAILURE,
    GET_USER_DATA,
    GET_OPPONENT_WINRATES,
    GET_ALLY_WINRATES,
    GET_AGGREGATE_USER_DATA,
    GET_AGGREGATE_MATCH_DATA,
}